
cat nn_pos_map.txt | awk -F ',' '{printf "%-30s %10s %10s %20s\n", $1, $2, $3, $4}' | sort -k2n
# user_id                                 1          0                 6041
# user_age                                2          0                    8
# user_gender                             3          0                    3
# user_occupation                         4          0                   21
# user_zip_code                           5          0                 3440
# user_movie_rate_cnt                    10          0                    6
# user_movie_rate_cnt_7day               11          0                    6
# user_movie_rate_cnt_15day              12          0                    6
# user_movie_rate_cnt_30day              13          0                    6
# user_avg_rate                          14          0                    2
# user_avg_rate_7day                     15          0                    2
# user_avg_rate_15day                    16          0                    2
# user_avg_rate_30day                    17          0                    2
# movie_id                              101          0                 3261
# movie_title                           102          0                 4408
# movie_genres                          103          0                   19
# movie_rate_count                      104          0                   11
# movie_avg_rate                        105          0                    9
# movie_genre_cnt                       106          0                    4
# item_hot_rank                         107          0                    4
# movie_publish_year                    108          0                    6
# context_time_hour                     201          0                   25
# context_time_area                     202          0                    7
# context_time_week                     203          0                    8
# context_is_weekend                    204          0                    3
# user_movie_rate                       301          0                 3639
# user_movie_rate_1day                  302          0                 3609
# user_movie_rate_3day                  303          0                 3612
# user_movie_rate_7day                  304          0                 3613
# user_movie_rate_15day                 305          0                 3617
# user_genres_rate                      306          0                   19
# user_genres_rate_1day                 307          0                   19
# user_genres_rate_3day                 308          0                   19
# user_genres_rate_7day                 309          0                   19
# user_genres_rate_15day                310          0                   19
# user_genres_rate_cnts                 312          0                   19
# user_genres_rate_cnt_1days            313          0                   19
# user_genres_rate_cnt_3days            314          0                   19
# user_genres_rate_cnt_7days            315          0                   19
# user_genres_rate_cnt_15days           316          0                   19
# user_top3_genres                      317          0                   19
# user_watch_same_genre                 351          0                    2
# user_watch_same_genre_1day            352          0                    2
# user_watch_same_genre_3day            353          0                    2
# user_watch_same_genre_7day            354          0                    2
# user_watch_same_genre_15day           355          0                    2
# user_same_genre_avg_rate              356          0                    6
# target                               3706