version = "3.8.3"
runner.dialect = scala212

maxColumn = 140
lineEndings = unix
encoding = UTF-8

indent.main = 2
indent.callSite = 2
indent.defnSite = 2

continuationIndent.callSite = 2
continuationIndent.defnSite = 2
continuationIndent.extends = 4

align.preset = none
align.openParenCallSite = false
align.openParenDefnSite = false

danglingParentheses = true
spaces.inImportCurlyBraces = true
rewrite.rules = [RedundantBraces, SortImports, PreferCurlyFors, AvoidInfix]
project.excludeFilters = [target/]
