// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/example/feature.proto

package org.tensorflow.example;

public interface Int64ListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.Int64List)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 value = 1 [packed = true, jstype = JS_STRING];</code>
   */
  java.util.List<java.lang.Long> getValueList();
  /**
   * <code>repeated int64 value = 1 [packed = true, jstype = JS_STRING];</code>
   */
  int getValueCount();
  /**
   * <code>repeated int64 value = 1 [packed = true, jstype = JS_STRING];</code>
   */
  long getValue(int index);
}
